INSERT INTO area (name) VALUES ('Motor Skills');
INSERT INTO area (name) VALUES ('Postural Ocular System');
INSERT INTO area (name) VALUES ('Muscle Tones');
INSERT INTO area (name) VALUES ('Eye Movements');
INSERT INTO area (name) VALUES ('Balance');
INSERT INTO area (name) VALUES ('Dynamic');
INSERT INTO area (name) VALUES ('Static');
INSERT INTO area (name) VALUES ('General Motor Coordination');
INSERT INTO area (name) VALUES ('Posture');
INSERT INTO area (name) VALUES ('Core Stability');
INSERT INTO area (name) VALUES ('Shoulder Stability');
INSERT INTO area (name) VALUES ('Hand-Eye Coordination');
INSERT INTO area (name) VALUES ('Motor Planning');
INSERT INTO area (name) VALUES ('Ideation');
INSERT INTO area (name) VALUES ('Planning');
INSERT INTO area (name) VALUES ('Execution');
INSERT INTO area (name) VALUES ('Bilateral Integration');
INSERT INTO area (name) VALUES ('Summetrical');
INSERT INTO area (name) VALUES ('Alternate');
INSERT INTO area (name) VALUES ('Laterality');
INSERT INTO area (name) VALUES ('Fine Motor Coordination');
INSERT INTO area (name) VALUES ('Perceptual Skills');
INSERT INTO area (name) VALUES ('Spatial Awareness');
INSERT INTO area (name) VALUES ('Position in Space');   
INSERT INTO area (name) VALUES ('Spatial Relations');   
INSERT INTO area (name) VALUES ('Directionality');
INSERT INTO area (name) VALUES ('Perceptual Consistency');
INSERT INTO area (name) VALUES ('Shapes');
INSERT INTO area (name) VALUES ('Colour');
INSERT INTO area (name) VALUES ('Self Care');
INSERT INTO area (name) VALUES ('Dressing');
INSERT INTO area (name) VALUES ('Eating');
INSERT INTO area (name) VALUES ('Sleeping');
INSERT INTO area (name) VALUES ('Toileting');